### ISSUE TITLE
好奇

### ISSUE THREAD

**Issue by shoukailiang** [ylsislove/make-a-little-progress-every-day#3]
> https://blog.csdn.net/Apple_Coco/article/details/113840717
你把图片保存在本地，再读出来发送到py
为什么不直接把内存中的图片发给py呢？

**Comment by ylsislove** [comment]
哈哈哈，所以我下一篇文章就是这样做的，Hololens2开发笔记-捕获照片到内存并上传至服务器（unity）：https://blog.csdn.net/Apple_Coco/article/details/113840722

**Comment by shoukailiang** [comment]
哈哈哈
